$("#target_01").click(function(){
	$('html,body').animate({
		"scrollTop":$("#miao1").offset().top
	},800)
})
			
$("#target_02").click(function(){
	$('html,body').animate({
		"scrollTop":$("#miao2").offset().top
	},800)
})
$("#target_03").click(function(){
	$('html,body').animate({
		"scrollTop":$("#miao3").offset().top
	},800)		
})
$("#target_04").click(function(){
	$('html,body').animate({
		"scrollTop":$("#miao4").offset().top
	},800)	
			console.log($("#miao4").offset().top);
})
$("#target_05").click(function(){
	$('html,body').animate({
		"scrollTop":$("#miao5").offset().top
	},800)		
})
$("#target_06").click(function(){
	$('html,body').animate({
		"scrollTop":$("#miao6").offset().top
	},800)		
})

